import time
import random
from pymodbus.server.sync import StartTcpServer
from pymodbus.device import ModbusDeviceIdentification
from pymodbus.datastore import ModbusSlaveContext, ModbusServerContext
from pymodbus.datastore.context import ModbusSparseDataBlock
from pymodbus.constants import Defaults
from threading import Thread
from datetime import datetime

# --- Configurable Parameters ---
SOLAR_POWER_MAX = 10000  # Maximum solar input power (watts, SolarEdge SE10K-RWB)
BATTERY_CAPACITY = 4600  # Battery capacity (Wh, SolarEdge Home Battery 48V)
BATTERY_VOLTAGE = 48  # Battery voltage (volts)
BATTERY_SOC_INIT = 50  # Initial State of Charge (%)
BATTERY_MAX_CHARGE_DISCHARGE = 5000  # Max charge/discharge power (watts)
LOAD_POWER = 3000  # Power consumed by loads (watts)
UPDATE_INTERVAL = 1  # Time interval for updates (seconds)
MODBUS_PORT = 5020  # Modbus TCP port
WR_ID = 1  # Default Modbus ID for the inverter
METER_ID = 2  # Default Modbus ID for the meter
BATTERY_ID = 3  # Default Modbus ID for the battery
ENABLE_RANDOM_VALUES = True  # Enable automatic random value generation for non-external values
ENABLE_SUN_POSITION = True  # Enable sun position-based power simulation
ENABLE_EVENT_TESTS = True  # Enable event-based tests
RANDOM_FACTOR = {
    "solar_power": 1000,  # Max random change for Solar Power (watts)
    "temperature": 1,  # Max random change for Device Temperature (°C)
    "status": [0, 1],  # Random device status values
}

# SunSpec-specific Modbus registers
SUNSPEC_BASE = 40000
REGISTER_MAP = {
    "AC_Current_L1": SUNSPEC_BASE + 6,  # AC Current Phase 1 (A)
    "AC_Current_L2": SUNSPEC_BASE + 7,  # AC Current Phase 2 (A)
    "AC_Current_L3": SUNSPEC_BASE + 8,  # AC Current Phase 3 (A)
    "AC_Voltage_L1": SUNSPEC_BASE + 9,  # AC Voltage Phase 1 (V)
    "AC_Voltage_L2": SUNSPEC_BASE + 10, # AC Voltage Phase 2 (V)
    "AC_Voltage_L3": SUNSPEC_BASE + 11, # AC Voltage Phase 3 (V)
    "AC_Power": SUNSPEC_BASE + 12,      # Total AC Power (W)
    "DC_Current": SUNSPEC_BASE + 13,    # DC Current (A)
    "DC_Voltage": SUNSPEC_BASE + 14,    # DC Voltage (V)
    "DC_Power": SUNSPEC_BASE + 15,      # DC Power (W)
    "SoC": SUNSPEC_BASE + 16,           # State of Charge (%)
    "Energy_Generated": SUNSPEC_BASE + 17,  # Total Energy Generated (Wh)
    "Energy_Consumed": SUNSPEC_BASE + 18,  # Total Energy Consumed (Wh)
    "Temperature": SUNSPEC_BASE + 19,   # Device Temperature (°C)
    "Status": SUNSPEC_BASE + 20,        # Device Status
}

# --- Initialize Data Storage ---
class CustomDataBlock(ModbusSparseDataBlock):
    def __init__(self, values):
        super().__init__(values)
        self.external_written = set()  # Tracks externally written registers

    def setValues(self, address, values):
        super().setValues(address, values)
        self.external_written.update(range(address, address + len(values)))
        print(f"Updated register {address}: {values}")

    def is_external_written(self, address):
        return address in self.external_written

store = ModbusSlaveContext(
    di=CustomDataBlock({}),
    co=CustomDataBlock({}),
    hr=CustomDataBlock({}),
    ir=CustomDataBlock({}),
    zero_mode=True
)
context = ModbusServerContext(slaves={WR_ID: store, METER_ID: store, BATTERY_ID: store}, single=False)

# --- Initialize Variables ---
soc = BATTERY_SOC_INIT  # State of Charge
solar_power = 0  # Solar power (watts)
battery_power = 0  # Battery power usage (watts)
total_energy_generated = 0  # Total energy generated by solar (kWh)
total_energy_consumed = 0  # Total energy consumed by loads (kWh)
device_temperature = 25  # Device temperature (°C)
device_status = 1  # Device status (1 = OK, 0 = Fault)

# --- Helper Functions ---
def calculate_solar_power():
    """Calculate solar power based on the current time of day."""
    now = datetime.now()
    hour = now.hour + now.minute / 60
    # Assume solar power peaks at 12:00 (noon) and tapers off towards sunrise and sunset
    if 6 <= hour <= 18:
        peak_power = SOLAR_POWER_MAX
        scale = max(0, 1 - abs(12 - hour) / 6)  # Scales between 0 and 1
        return int(peak_power * scale)
    return 0

def apply_event_tests():
    """Apply event-based tests such as load changes, battery swaps, or outages."""
    global LOAD_POWER, battery_power
    event = random.choice(["load_change", "battery_swap", "grid_outage", None])

    if event == "load_change":
        LOAD_POWER = random.randint(1000, 5000)
        print(f"Event: Load change, new load power = {LOAD_POWER}W")

    elif event == "battery_swap":
        battery_power = 0  # Reset battery usage
        print("Event: Battery swap, resetting battery power.")

    elif event == "grid_outage":
        LOAD_POWER = 0
        print("Event: Grid outage, setting load power to 0.")

# --- Simulation Logic ---
def update_simulation():
    global soc, solar_power, battery_power, total_energy_generated, total_energy_consumed, device_temperature, device_status

    while True:
        # Calculate solar power based on sun position
        if ENABLE_SUN_POSITION:
            solar_power = calculate_solar_power()

        # Apply event-based tests
        if ENABLE_EVENT_TESTS:
            apply_event_tests()

        # Simulate load consumption and adjust battery power if not externally written
        if not store.is_external_written(REGISTER_MAP["DC_Power"]):
            net_power = solar_power - LOAD_POWER

            if net_power > 0:
                # Excess power charges the battery
                charge_power = min(net_power, BATTERY_MAX_CHARGE_DISCHARGE, (BATTERY_CAPACITY - (soc / 100 * BATTERY_CAPACITY)))
                battery_power = charge_power
                soc = min(100, soc + (charge_power / BATTERY_CAPACITY * 100))
            else:
                # Insufficient power, discharge battery
                discharge_power = min(abs(net_power), BATTERY_MAX_CHARGE_DISCHARGE, soc / 100 * BATTERY_CAPACITY)
                battery_power = -discharge_power
                soc = max(0, soc - (discharge_power / BATTERY_CAPACITY * 100))

        # Calculate per-phase values
        phase_power = solar_power / 3
        phase_current = phase_power / 230

        # Update total energy counters
        total_energy_generated += solar_power / 1000 / 3600 * UPDATE_INTERVAL
        total_energy_consumed += LOAD_POWER / 1000 / 3600 * UPDATE_INTERVAL

        # Update Modbus registers
        store.setValues(3, REGISTER_MAP["AC_Current_L1"], [int(phase_current)])
        store.setValues(3, REGISTER_MAP["AC_Current_L2"], [int(phase_current)])
        store.setValues(3, REGISTER_MAP["AC_Current_L3"], [int(phase_current)])
        store.setValues(3, REGISTER_MAP["AC_Voltage_L1"], [230])
        store.setValues(3, REGISTER_MAP["AC_Voltage_L2"], [230])
        store.setValues(3, REGISTER_MAP["AC_Voltage_L3"], [230])
        store.setValues(3, REGISTER_MAP["AC_Power"], [int(solar_power)])
        store.setValues(3, REGISTER_MAP["DC_Current"], [int(battery_power / BATTERY_VOLTAGE)])
        store.setValues(3, REGISTER_MAP["DC_Voltage"], [BATTERY_VOLTAGE])
        store.setValues(3, REGISTER_MAP["DC_Power"], [int(battery_power)])
        store.setValues(3, REGISTER_MAP["SoC"], [int(soc)])
        store.setValues(3, REGISTER_MAP["Energy_Generated"], [int(total_energy_generated * 1000)])
        store.setValues(3, REGISTER_MAP["Energy_Consumed"], [int(total_energy_consumed * 1000)])
        store.setValues(3, REGISTER_MAP["Temperature"], [int(device_temperature)])
        store.setValues(3, REGISTER_MAP["Status"], [device_status])

        # Print console output for debugging
        print(f"Solar Power: {solar_power}W | Battery Power: {battery_power}W | SoC: {soc}% | ",
              f"Energy Generated: {total_energy_generated:.3f}kWh | Energy Consumed: {total_energy_consumed:.3f}kWh | ",
              f"Temperature: {device_temperature:.1f}°C | Status: {device_status}")

        time.sleep(UPDATE_INTERVAL)

def display_registers():
    print("\n--- Current Modbus Register Values ---")
    for name, address in REGISTER_MAP.items():
        value = store.getValues(3, address, count=1)[0]
        print(f"{name} (Register {address}): {value}")
    print("--------------------------------------\n")

# --- Start Simulation ---
def start_modbus_server():
    identity = ModbusDeviceIdentification()
    identity.VendorName = 'SolarEdge'
    identity.ProductCode = 'SE-Simulator'
    identity.ProductName = 'SolarEdge Simulator'
    identity.ModelName = 'SE10K-RWB'
    identity.MajorMinorRevision = '1.0'

    StartTcpServer(context, identity=identity, address=("0.0.0.0", MODBUS_PORT))

# Run simulation logic in a separate thread
simulation_thread = Thread(target=update_simulation)
simulation_thread.daemon = True
simulation_thread.start()

# Example: Allow user to manually query register values
if __name__ == "__main__":
    query_thread = Thread(target=start_modbus_server)
    query_thread.daemon = True
    query_thread.start()

    while True:
        cmd = input("Type 'show' to display register values or 'exit' to quit: ").strip().lower()
        if cmd == "show":
            display_registers()
        elif cmd == "exit":
            print("Exiting...")
            break
          
